name: AdvancedFix
main: UrHuckle\AdvancedFix\Loader
version: 0.0.1
api: 3.0.0
author: urhuckleberry

permissions:
  af.command.use:
    default: op
  af.command.hand:
    default: op
  af.command.all:
    default: op
